### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by Benzlxs** [bradyz/cross_view_transformers#1]
Hi Bradyz, many thanks for sharing this amzing work, the idea is elegant. Currently, I am trying to use the code for 3D object detection task, but it takes long time to train the model. Would you mind providing well-pretrained model to speedup training process?

**Comment by bradyz** [comment]
Check out `scripts/example.ipynb` for a link to a pretrained model and how to load it

I'll update this in the main README soon along with some newer models

Is your code public? I can take a look
Most models take about 8 hours on a 4 GPU machine

**Comment by Benzlxs** [comment]
Thanks.

**Comment by bradyz** [comment]
Great, looking forward to it - I have not trained models at that resolution (the cross attention takes a lot of memory) so let me know what you do to get it to work
