### ISSUE TITLE
Model parameter count

### ISSUE THREAD

**Issue by vztu** [bradyz/cross_view_transformers#14]
Hi Brady, thanks for the great work!

I have a question regarding the model parameters. In your paper, you have reported `5M` in Table 1 on nuscenes. However, I run your code with the default yaml config, and the log says `1.1M` parameters. Did I miss anything? 

![image](https://user-images.githubusercontent.com/43280278/168724330-417aa10d-180b-41de-bdad-bb06565a8fca.png)

**Comment by bradyz** [comment]
At the time of the paper we had included weights of the entire backbone (efficientnet),
when much of the later layers weren't actually used.
So after culling those layers, this 1.1M params is the correct number.

We'll fix the paper's numbers in a future revision, thanks for bringing this up 👍
