### ISSUE TITLE
Warning : Grad strdies do not match bucket view strides & Error : internal database error

### ISSUE THREAD

**Issue by NickHezhuolin** [bradyz/cross_view_transformers#25]
When I used source code training whole nuscenes dataset, model will be shutdown at epoch 6.
  
rank_zero_warn(
Epoch 6:  44%|█████████████████████████████████████████████████████▎                                                                    | 1866/4270 [00:00<?, ?it/s]

Messages form TERMINAL:
[W reducer.cpp:347] Warning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [2, 64, 1, 1], strides() = [64, 1, 64, 64]
bucket_view.sizes() = [2, 64, 1, 1], strides() = [64, 1, 1, 1] (function operator())
[W reducer.cpp:347] Warning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [2, 64, 1, 1], strides() = [64, 1, 64, 64]
bucket_view.sizes() = [2, 64, 1, 1], strides() = [64, 1, 1, 1] (function operator())

wandb debug logs message:
2022-07-19 21:15:58,526 ERROR   MainThread:2484870 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-07-19 21:15:58,527 ERROR   MainThread:2484870 [internal_api.py:execute():144] {"error":"internal database error"}

So how should I modify it so that I can train normally?

**Comment by bradyz** [comment]
This looks like an error from wandb - maybe their servers were down during training or your job lost internet connection.
The `Grad strides do not match bucket view strides` the message always occurs during training, but won't cause any errors.

**Comment by NickHezhuolin** [comment]
thanks
