### ISSUE TITLE
Scripts to generate the labels

### ISSUE THREAD

**Issue by DerrickXuNu** [bradyz/cross_view_transformers#3]
Hi Brady,

Thanks for your great work and clean coding style! I am wondering do you still have the scripts to generate the cvt_labels_nuscenes? If so, would you be willing to share it? Look forward to your reply.

**Comment by bradyz** [comment]
flattered by your kind words :)

i've included a short [readme](https://github.com/bradyz/cross_view_transformers/blob/master/docs/label_generation.md) on how to generate the labels, but please follow up here if you run into trouble so I can improve the docs

Also, if you have a fast enough machine, with a little bit of code changes you could make the experiments render the labels on the fly, let me know if you are interested in this

**Comment by DerrickXuNu** [comment]
Thanks for your quick reply! I do have some fast machine, I'd appreciate it if you could show me how to render the labels during runtime.

**Comment by GoroYeh56** [comment]
Hi, I want to ask a follow-up here:

In the `generate_data.py`, how should we change so that it will generate labels that segment 11 classes?
